
title: Fakultní sociologie, z. s. 
email: info@fakultnisociologie.cz
baseurl: "" 
url: "http://fakultnisociologie.cz" 
description: Fakultní sociologie, z. s. pomáhá studentům sociologie, publikuje a realizuje vlastní výzkumy a usiluje o podporu volnočasových aktivit studentů, které přispívají k rozvoji sociologie. 

facebook_username: fakultnisociologie
rss: rss
google_analytics: UA-NNNNNNNN-N


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
