
title: Fakultní sociologie, z. s. 
email: info@fakultnisociologie.cz
baseurl: "" 
url: "http://fakultnisociologie.cz" 



# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
