
title: Fakultní sociologie, z.s. 
email: info@fakultnisociologie.cz
description: > 
  Blog neziskové organizace Fakultní sociologie, z.s.  
baseurl: "" 
url: "http://fakultnisociologie.cz" 



# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
