
title: Fakultní sociologie, z. s. 
email: info@fakultnisociologie.cz
baseurl: "" 
url: "http://fakultnisociologie.cz" 
description: Fakultní sociologie, z. s. pomáhá studentům sociologie a usiluje o zprostředkování možnost dělat sociologii, která má skutečné důsledky, již v průběhu studia.



# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
