
title: Fakultní sociologie, z. s. 
email: info@fakultnisociologie.cz
baseurl: "" 
url: "http://fakultnisociologie.cz" 
description: Fakultní sociologie, z. s. pomáhá studentům sociologie, usiluje o podporu jejich volnočasových aktivit, které přispívají k rozvoji sociologie, či zvyšují jejich sociologické dovednosti. Zároveň vytváří vlastní poznání o sociálních okolnostech vzdělávacího systému, masové univerzity a postavení sociologie a blízkých oborů v současné české společnosti. 

facebook_username: fakultnisociologie
rss: rss
google_analytics: UA-NNNNNNNN-N


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
